packages:
  - "integration"
  - "integration/helpers/node-template"
  - "integration/helpers/vite-template"
  - "packages/react-router"
  - "packages/react-router-dom"
  - "packages/react-router-dom-v5-compat"
  - "packages/react-router-native"
  - "packages/remix-dev"
  - "packages/remix-express"
  - "packages/remix-node"
  - "packages/remix-serve"
  - "packages/remix-server-runtime"
  - "packages/remix-testing"
  - "packages/router"
  - "playground/compiler"
  - "playground/compiler-express"
  - "playground/compiler-spa"
  - "playground/rsc"
