packages:
  - "integration"
  - "integration/helpers/*"
  - "packages/*"
  - "playground/*"

catalog:
  "@types/react": ^18.0.27
  "@types/react-dom": ^18.0.10
  "@vitejs/plugin-rsc": ~0.5.18
  react: ^19.2.4
  react-dom: ^19.2.4
  react-server-dom-parcel: ^19.2.4
  react-server-dom-webpack: ^19.2.4
  typescript: ^5.4.5
  tsup: ^8.3.0
  wireit: 0.14.9

catalogs:
  react-canary:
    "@types/react": ^19.2.7
    "@types/react-dom": ^19.2.3
    react: ^19.2.4
    react-dom: ^19.2.4
    react-server-dom-parcel: ^19.2.4
    react-server-dom-webpack: ^19.2.4
  vite-7:
    vite: ^7.3.1
