packages:
  - "integration"
  - "integration/helpers/*"
  - "packages/*"
  - "playground/*"

catalog:
  "@types/react": ^18.0.27
  "@types/react-dom": ^18.0.10
  "@vitejs/plugin-rsc": ~0.5.6
  react: canary
  react-dom: canary
  react-server-dom-parcel: canary
  react-server-dom-webpack: canary
  typescript: ^5.4.5
  tsup: ^8.3.0
  wireit: 0.14.9

overrides:
  react: canary
  react-dom: canary
  react-server-dom-parcel: canary
  react-server-dom-webpack: canary
