packages:
  - "integration"
  - "integration/helpers/*"
  - "packages/*"
  - "playground/*"

catalog:
  "@types/react": ^18.0.27
  "@types/react-dom": ^18.0.10
  react: ^19.2.1
  react-dom: ^19.2.1
  typescript: ^5.4.5
  tsup: ^8.3.0
  wireit: 0.14.9
