packages:
  - "integration"
  - "integration/helpers/*"
  - "packages/*"
  - "playground/*"
  - "scripts"

catalog:
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-rsc": ~0.5.21
  react: ^19.2.6
  react-dom: ^19.2.6
  react-server-dom-webpack: ^19.2.6
  typescript: ^6.0.3
  tsup: ^8.5.1
  wireit: 0.14.9
