/**
 * An augmentable interface users can modify in their app-code to opt into
 * future-flag-specific types
 */
export interface Future {
  // We list the potential fields here in comments strictly for clarity.
  // They will be generated by the react-router/dev/typegen/generate.ts module
  //
  // v8_middleware: boolean
}

// prettier-ignore
export type MiddlewareEnabled =
  Future extends { v8_middleware: infer T extends boolean; } ? T : false
