name: 🐛 Bug Report
description: Something is wrong with React Router
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping to improve React Router!

        Please note that **all** bugs must have a **minimal** reproduction, meaning
        that it is not just pointing to a deployed site or a branch in your existing
        application.  Please refer to the [Bug/Issue Process Guidelines](https://github.com/remix-run/react-router/blob/main/GOVERNANCE.md#bugissue-process)
        for more information.

        ## If you are using **Framework Mode**, you have 2 preferred options:

        **Option 1** - Create a failing integration test

        🏆 The most helpful reproduction is to use our _bug report integration test_ template:

        1. [Fork `remix-run/react-router`](https://github.com/remix-run/react-router/fork)
        2. Open [`integration/bug-report-test.ts`](https://github.com/remix-run/react-router/blob/dev/integration/bug-report-test.ts) in your editor
        3. Follow the instructions to create a failing bug report test
        4. Link to your forked branch with the failing test in this issue

        ## Option 2: Create a **minimal** reproduction

        - 🥇 Link to a [StackBlitz](https://reactrouter.com/new) environment
        - 🥈 Link to a GitHub repository containing a minimal reproduction app

        ## If you are using **Data** or **Declarative Mode**:

        Create a **minimal** reproduction

        - 🥇 Link to a CodeSandbox repro: [TS](https://codesandbox.io/templates/react-vite-ts) | [JS](https://codesandbox.io/templates/react-vite)
        - 🥈 Link to a GitHub repository containing a minimal reproduction app

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Link to reproduction and steps to reproduce the behavior
      placeholder: Go to https://stackblitz.com/edit/... and click the "Submit" button
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --npmPackages '{vite,react-router,@react-router/*}' --binaries --browsers`
      render: shell
      placeholder: System, Binaries, Browsers
    validations:
      required: true
  - type: dropdown
    id: package-manager
    attributes:
      label: Used Package Manager
      description: Select the used package manager
      options:
        - npm
        - yarn
        - pnpm
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
