#!/bin/sh
mkdir -p dist
NODE_ENV=production node_modules/.bin/browserify index.js -t browserify-shim -t envify --detect-globals false -s ReactRouter > dist/react-router.js
node_modules/.bin/uglifyjs dist/react-router.js --compress warnings=false > dist/react-router.min.js
