#!/bin/sh
mkdir -p dist
NODE_ENV=production node_modules/.bin/browserify modules/main.js --detect-globals false -s ReactRouter > dist/react-router.js
node_modules/.bin/uglifyjs dist/react-nested-router.js --compress warnings=false > dist/react-router.min.js
