#!/bin/sh
mkdir -p dist
NODE_ENV=production node_modules/.bin/browserify modules/index.js -t browserify-shim -t envify --detect-globals false -s ReactRouter > dist/react-router.js
node_modules/.bin/uglifyjs dist/react-router.js --compress warnings=false > dist/react-router.min.js
echo "gzipped, the global build is:"
echo "`gzip -c dist/react-router.min.js | wc -c` bytes"

