name: 💬 Release Comments

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  comment:
    name: 📝 Comment on released issues/pull requests
    runs-on: ubuntu-latest
    permissions:
      issues: write # enable commenting on released issues
      pull-requests: write # enable commenting on released pull requests
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24 # Needed for node TS support
          cache: "pnpm"

      - name: 📥 Install deps
        run: pnpm install --frozen-lockfile

      - name: 📝 Comment on released issues and pull requests
        env:
          GH_TOKEN: ${{ github.token }}
        run: pnpm run release-comments
