name: Unit Test

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
    paths-ignore:
      - "docs/**"
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: "Node ${{ matrix.node }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - 22.22
          - 24

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
          check-latest: true

      - name: Setup wireit cache
        uses: google/wireit@setup-github-actions-caching/v2.0.4

      - name: Disable GitHub Actions Annotations
        run: |
          echo "::remove-matcher owner=tsc::"
          echo "::remove-matcher owner=eslint-compact::"
          echo "::remove-matcher owner=eslint-stylish::"

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test
